import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Full Stack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='px-3 py-2'>
        <p className='text-2xl'>Welcome</p>
      </main>

    </div>
  )
}
